spring:
  application:
    name: idmhperu

  datasource:
    url: jdbc:mysql://31.97.133.166:3306/idmhperu_test
    username: user-idmhperu
    password: Secretoidmh2026.
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
      #format_sql: true

  jackson:
    time-zone: America/Lima

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB

server:
  port: 8090

jwt:
  secret:
    key: 6EAB10E2B4F3AASDG912F9C32C73F0AH41J21A9F5FCE3C423F6D489E7BA84DA82

custom:
  server:
    hostname: https://api-test.facturacion-idmhperu.website